# Generated by Django 5.2.4 on 2025-08-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='class_groups', to='tracker.user'),
        ),
    ]
