# Generated by Django 5.2.4 on 2025-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_classgroup_teacher_classgroup_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, null=True, related_name='class_groups', to='tracker.user'),
        ),
    ]
