# Generated by Django 5.2.4 on 2025-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tests_testresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='test',
            field=models.CharField(max_length=100),
        ),
    ]
