# Generated by Django 5.2.4 on 2025-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_student_date_of_birth_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
